baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Writings'
pageRef = '/writings'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
