name = 'Eudaimonia'
license = 'MIT'
licenselink = 'https://github.com/evnmrk/eudaimonia/blob/main/LICENSE'
description = 'My custom theme for my personal blog.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/evnmrk/eudaimonia'

# If you have a running demo of the theme
demosite = 'https://evnmrk.xyz/'

# Taxonomy terms
tags = ['blog']
# features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Evan'
  homepage = 'https://evnmrk.xyz'